a = "akshay Aakash" #strings are immutable
print(a)
print(a.upper())
print(a.lower())
print(a.replace("Akshay","sanket"))
print(len(a))
print(a.split(" "))
print(a.capitalize())
print(a.center(40))
print(a.count("a"))
print(a.endswith("a"))
print(a.find("Aakash"))
